"""
ml/secagg.py
══════════════════════════════════════════════════════════════════════
Secure Aggregation (SecAgg) — Bonawitz et al. 2017
"Practical Secure Aggregation for Privacy-Preserving Machine Learning"
https://dl.acm.org/doi/10.1145/3133956.3133982

What it does
────────────
  The server learns only the *sum* of client model updates.
  It never sees any individual client's gradient — even if it is
  honest-but-curious (HbC adversary model).

Protocol summary (simplified single-server variant)
────────────────────────────────────────────────────
  Setup (once per round):
    1. Each pair of clients (i, j) agree on a shared random seed
       s_{ij} using Diffie-Hellman-style key agreement.  (Here we
       simulate this: the server generates seeds on behalf of pairs,
       which is fine for a simulation — in production each client
       would run DH independently.)

    2. From s_{ij}, both clients derive a pseudorandom mask vector
       m_{ij} of the same dimension as the model update:
         if i < j:  client i adds  +PRG(s_{ij})   to its update
                    client j adds  −PRG(s_{ij})    to its update
       The masks cancel in the sum:  Σ m_{ij} = 0

    3. Each client also adds a self-mask m_{ii} = PRG(s_{ii})
       derived from its own private seed s_{ii}.  This self-mask
       must be unmasked by the server using the client's share.

  Aggregation:
    4. Each client sends:  masked_update_i = update_i + Σ_j m_{ij} + m_{ii}
    5. Server sums all masked updates:
         Σ masked_update_i = Σ update_i  +  Σ_{i≠j} m_{ij}  +  Σ m_{ii}
       The pairwise terms cancel (step 2), leaving:
         Σ masked_update_i = Σ update_i + Σ m_{ii}

    6. Server collects self-mask seeds from surviving clients and
       reconstructs Σ m_{ii}, then subtracts to recover Σ update_i.

  Dropout handling (Bonawitz §4.4):
    If a client drops out after sending its masked update but before
    revealing its self-mask, the server uses Shamir Secret Sharing:
    each client's self-seed is split into (t-of-n) shares distributed
    to other clients.  The t threshold must be ≤ number of surviving
    clients.  If too many clients drop out, the round is aborted.

    Here we implement a simpler "honest dropout" model: dropped clients
    reveal their self-seed shares to the server directly (equivalent to
    threshold=1, which is sufficient for simulation purposes).

Implementation notes
────────────────────
  • All arithmetic is over ℝ (floats), not a finite field.
    Production SecAgg works modulo a large prime; floats are used here
    because the downstream aggregation is floating-point FedAvg.

  • PRG = seeded Python random (Mersenne Twister).  Production systems
    use AES-CTR or ChaCha20 as a PRG.  The security argument holds as
    long as seeds are unknown to the server before unmasking.

  • Shared seeds between pairs are generated by the server for
    simulation.  In production each client runs DH key exchange with
    every other client; the server never sees the pairwise seeds.

Classes
───────
  SecAggServer    — orchestrates the protocol for one FL round
  SecAggClient    — represents one simulated client
  SecAggRound     — result of one complete SecAgg round
"""

from __future__ import annotations

import hashlib
import logging
import random
import struct
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)


# ════════════════════════════════════════════════════════════════════════════
#  Pseudorandom Generator (PRG)
# ════════════════════════════════════════════════════════════════════════════

def _prg_vector(seed: int, length: int, scale: float = 1e-4) -> list[float]:
    """
    Deterministic pseudorandom vector from an integer seed.

    Uses hashlib + struct to expand the seed into `length` floats in
    [-scale, +scale].  The result is the same on every call with the
    same (seed, length) — this is the critical property for masks to
    cancel between two clients who share a seed.

    scale is chosen small (1e-4) so masks have negligible effect on
    model accuracy after cancellation, but are non-trivially large
    enough to hide individual updates from the server during aggregation.
    """
    rng   = random.Random(seed)
    return [rng.uniform(-scale, scale) for _ in range(length)]


def _prg_scalar(seed: int, scale: float = 1e-4) -> float:
    """Deterministic pseudorandom scalar from a seed."""
    return random.Random(seed).uniform(-scale, scale)


def _derive_pairwise_seed(base_seed: int, i: int, j: int) -> int:
    """
    Deterministic seed for the (i, j) pair, symmetric: same result
    for (i,j) and (j,i).  Uses SHA-256 to mix inputs.
    """
    key = struct.pack(">QQQ", base_seed, min(i, j), max(i, j))
    digest = hashlib.sha256(key).digest()
    return int.from_bytes(digest[:8], "big")


def _derive_self_seed(base_seed: int, i: int) -> int:
    """Deterministic self-mask seed for client i."""
    key = struct.pack(">QQ", base_seed, i)
    digest = hashlib.sha256(key).digest()
    return int.from_bytes(digest[:8], "big")


# ════════════════════════════════════════════════════════════════════════════
#  Shamir Secret Sharing  (t-of-n)
# ════════════════════════════════════════════════════════════════════════════

class ShamirSecretSharing:
    """
    Integer Shamir Secret Sharing over a large prime field.

    The secret (a seed integer) is split into n shares such that
    any t shares can reconstruct the secret, but t-1 shares reveal
    nothing.

    Prime chosen as the 13th Mersenne prime (2^521 - 1) for large
    field size.  For simulation purposes a smaller safe prime is fine.
    """

    # Safe prime: 2^31 - 1 (Mersenne prime M31) — small but sufficient
    # for simulation.  Production: use a 256-bit+ prime.
    PRIME = (1 << 31) - 1

    @staticmethod
    def _poly_eval(coeffs: list[int], x: int, p: int) -> int:
        """Evaluate polynomial with given coefficients at x (mod p)."""
        result = 0
        for c in reversed(coeffs):
            result = (result * x + c) % p
        return result

    @staticmethod
    def split(secret: int, n: int, t: int) -> list[tuple[int, int]]:
        """
        Split `secret` into n shares with threshold t.
        Returns list of (x, y) pairs where x ∈ {1..n}.
        """
        p = ShamirSecretSharing.PRIME
        secret_mod = secret % p
        # Random polynomial of degree (t-1) with constant term = secret
        coeffs = [secret_mod] + [random.randrange(p) for _ in range(t - 1)]
        return [(x, ShamirSecretSharing._poly_eval(coeffs, x, p))
                for x in range(1, n + 1)]

    @staticmethod
    def reconstruct(shares: list[tuple[int, int]]) -> int:
        """
        Lagrange interpolation to recover secret from t (or more) shares.
        Returns the secret modulo PRIME.
        """
        p = ShamirSecretSharing.PRIME
        secret = 0
        for i, (xi, yi) in enumerate(shares):
            num = den = 1
            for j, (xj, _) in enumerate(shares):
                if i != j:
                    num = (num * (-xj)) % p
                    den = (den * (xi - xj)) % p
            # Modular inverse via Fermat's little theorem (p is prime)
            lagrange = (yi * num % p * pow(den, p - 2, p)) % p
            secret   = (secret + lagrange) % p
        return secret


# ════════════════════════════════════════════════════════════════════════════
#  SecAgg Client
# ════════════════════════════════════════════════════════════════════════════

@dataclass
class SecAggClient:
    """
    Represents one simulated FL client participating in SecAgg.

    In a real deployment each client is a separate process/device.
    Here we simulate all clients in-process on the server, which is
    equivalent for testing the protocol correctness — the server
    code path only ever sees masked updates.
    """
    client_id:    int
    n_clients:    int
    n_features:   int
    threshold:    int        # Shamir reconstruction threshold
    round_seed:   int        # shared round seed (from server)

    # Set during masking phase
    _pairwise_seeds: dict[int, int] = field(default_factory=dict, repr=False)
    _self_seed:      int            = field(default=0,            repr=False)
    _self_seed_shares: list         = field(default_factory=list, repr=False)

    def setup(self) -> None:
        """
        Derive all pairwise seeds and the self-seed for this round.
        In production this is done via DH with each peer; here we
        use the deterministic PRG so the simulation is reproducible.
        """
        i = self.client_id
        self._pairwise_seeds = {
            j: _derive_pairwise_seed(self.round_seed, i, j)
            for j in range(self.n_clients)
            if j != i
        }
        self._self_seed = _derive_self_seed(self.round_seed, i)

        # Split self-seed into (threshold)-of-(n_clients) Shamir shares
        # distributed to all other clients (server holds them for dropout recovery)
        self._self_seed_shares = ShamirSecretSharing.split(
            self._self_seed, self.n_clients, self.threshold
        )

    def mask(self, update: list[float]) -> list[float]:
        """
        Apply pairwise masks + self-mask to the model update.

        For each pair (i, j) with i < j:
          client i adds  +PRG(s_{ij})
          client j adds  −PRG(s_{ij})
        These cancel in the sum.

        Self-mask PRG(s_{ii}) is always added; server reconstructs and
        subtracts it using shares revealed after aggregation.
        """
        i      = self.client_id
        n      = len(update)
        masked = list(update)

        # Pairwise masks
        for j, seed in self._pairwise_seeds.items():
            mask_vec = _prg_vector(seed, n)
            sign     = +1 if i < j else -1
            for k in range(n):
                masked[k] += sign * mask_vec[k]

        # Self-mask
        self_mask = _prg_vector(self._self_seed, n)
        for k in range(n):
            masked[k] += self_mask[k]

        return masked

    def get_self_seed_share(self, recipient_id: int) -> tuple[int, int]:
        """Return this client's self-seed share intended for `recipient_id`."""
        # Share x = recipient_id + 1  (shares are 1-indexed)
        return self._self_seed_shares[recipient_id]

    def get_all_self_seed_shares(self) -> list[tuple[int, int]]:
        """Return all shares of this client's self-seed."""
        return self._self_seed_shares


# ════════════════════════════════════════════════════════════════════════════
#  SecAgg Server
# ════════════════════════════════════════════════════════════════════════════

@dataclass
class SecAggRound:
    """Result of one SecAgg aggregation round."""
    aggregated_weights:  list[float]    # recovered Σ w_i (unmasked sum)
    aggregated_bias:     float          # recovered Σ b_i (unmasked scalar)
    n_clients_survived:  int
    n_clients_dropped:   int
    masking_overhead_ms: float          # wall time for mask/unmask ops
    verified:            bool           # True if mask cancellation verified
    secagg_summary:      dict           # diagnostic info


class SecAggServer:
    """
    Server-side SecAgg coordinator for one FL round.

    Responsibilities:
      1. Generate and distribute round seed + pairwise seeds
      2. Coordinate client masking
      3. Aggregate masked updates
      4. Collect self-seed shares from surviving clients
      5. Reconstruct and subtract self-masks → recover Σ updates
      6. Handle dropped clients via Shamir reconstruction

    Usage
    ─────
        server = SecAggServer(
            n_clients=5, n_features=10, threshold=3
        )
        agg_w, agg_b = server.aggregate_round(client_updates, client_biases)
    """

    def __init__(
        self,
        n_clients:   int,
        n_features:  int,
        threshold:   int  = 0,           # 0 = auto: ceil(n_clients / 2)
        dropout_rate: float = 0.0,        # fraction of clients to simulate dropping
    ) -> None:
        if n_clients < 2:
            raise ValueError("SecAgg requires at least 2 clients.")
        self.n_clients   = n_clients
        self.n_features  = n_features
        self.threshold   = threshold if threshold > 0 else max(2, (n_clients + 1) // 2)
        self.dropout_rate = dropout_rate

        if self.threshold > n_clients:
            raise ValueError(
                f"threshold ({self.threshold}) cannot exceed n_clients ({n_clients})"
            )

    def aggregate_round(
        self,
        weight_updates: list[list[float]],  # one list[float] per client
        bias_updates:   list[float],         # one float per client
        round_seed:     Optional[int] = None,
    ) -> SecAggRound:
        """
        Run one complete SecAgg round.

        Parameters
        ──────────
        weight_updates : list of n_clients weight-update vectors (Δw)
        bias_updates   : list of n_clients bias updates (Δb)
        round_seed     : optional reproducibility seed; random if None

        Returns
        ───────
        SecAggRound with .aggregated_weights and .aggregated_bias
        being the unmasked sum  Σ_i Δw_i  and  Σ_i Δb_i  across
        surviving clients.
        """
        import time
        t0 = time.time()

        n = self.n_clients
        if len(weight_updates) != n or len(bias_updates) != n:
            raise ValueError(
                f"Expected {n} client updates, got "
                f"{len(weight_updates)} weight and {len(bias_updates)} bias."
            )

        if round_seed is None:
            round_seed = random.randrange(1 << 62)

        # ── Phase 1: Client setup (derive seeds, prepare Shamir shares) ──
        clients = [
            SecAggClient(
                client_id=i,
                n_clients=n,
                n_features=self.n_features,
                threshold=self.threshold,
                round_seed=round_seed,
            )
            for i in range(n)
        ]
        for c in clients:
            c.setup()

        # ── Phase 2: Simulate dropout ────────────────────────────────────
        n_drop   = int(n * self.dropout_rate)
        # Drop the last `n_drop` clients (deterministic for reproducibility)
        survived = list(range(n - n_drop))
        dropped  = list(range(n - n_drop, n))

        if len(survived) < self.threshold:
            raise RuntimeError(
                f"Too many dropouts: {len(dropped)} dropped, "
                f"only {len(survived)} survived (threshold={self.threshold}). "
                f"Reduce dropout_rate or lower threshold."
            )

        logger.debug(
            "SecAgg round: %d clients, %d survived, %d dropped (threshold=%d)",
            n, len(survived), len(dropped), self.threshold,
        )

        # ── Phase 3: Surviving clients mask their updates ────────────────
        masked_weights = []
        masked_biases  = []

        for i in survived:
            c         = clients[i]
            masked_w  = c.mask(weight_updates[i])
            # Mask the scalar bias: treat as length-1 vector
            masked_b  = c.mask([bias_updates[i]])[0]
            masked_weights.append(masked_w)
            masked_biases.append(masked_b)

        # ── Phase 4: Server aggregates masked updates ────────────────────
        nf = self.n_features
        agg_w_masked = [
            sum(masked_weights[s][k] for s in range(len(survived)))
            for k in range(nf)
        ]
        agg_b_masked = sum(masked_biases)

        # ── Phase 5: Reconstruct and subtract self-masks ─────────────────
        # Each surviving client reveals its self-seed (or we reconstruct
        # it from the Shamir shares held by surviving clients).
        #
        # For surviving clients: server directly learns self-seed
        # For dropped clients: server uses Shamir to reconstruct self-seed
        # (threshold shares are available from surviving clients)

        total_self_mask_w = [0.0] * nf
        total_self_mask_b = 0.0

        # Self-masks of surviving clients
        for i in survived:
            c          = clients[i]
            self_mask_w = _prg_vector(c._self_seed, nf)
            self_mask_b = _prg_vector(c._self_seed, 1)[0]
            for k in range(nf):
                total_self_mask_w[k] += self_mask_w[k]
            total_self_mask_b += self_mask_b

        # Self-masks of dropped clients (reconstructed via Shamir)
        for i in dropped:
            # Collect threshold shares from surviving clients
            # Share index for client i held by client j is shares[i]
            # (each client splits their own seed and distributes shares)
            shares_for_i = []
            for j in survived[:self.threshold]:
                # Client j holds a share of client i's self-seed
                # (in this simulation, client i shared their seed with everyone)
                share = clients[i].get_self_seed_share(j)
                shares_for_i.append(share)

            reconstructed_seed = ShamirSecretSharing.reconstruct(
                shares_for_i[:self.threshold]
            )
            # The reconstructed seed is mod PRIME; we use it as-is for PRG
            self_mask_w = _prg_vector(reconstructed_seed, nf)
            self_mask_b = _prg_vector(reconstructed_seed, 1)[0]
            for k in range(nf):
                total_self_mask_w[k] += self_mask_w[k]
            total_self_mask_b += self_mask_b

        # ── Phase 6: Unmask → recover true aggregate ─────────────────────
        agg_w = [agg_w_masked[k] - total_self_mask_w[k] for k in range(nf)]
        agg_b = agg_b_masked - total_self_mask_b

        elapsed_ms = (time.time() - t0) * 1000

        # ── Verification: compare with plaintext sum (debug only) ─────────
        # In production this is never computed — it would defeat SecAgg.
        # Here we use it to assert correctness in tests.
        true_sum_w = [
            sum(weight_updates[i][k] for i in survived)
            for k in range(nf)
        ]
        true_sum_b = sum(bias_updates[i] for i in survived)

        err_w = max(abs(agg_w[k] - true_sum_w[k]) for k in range(nf))
        err_b = abs(agg_b - true_sum_b)
        verified = (err_w < 1e-6 and err_b < 1e-6)

        if not verified:
            logger.warning(
                "SecAgg verification failed: max_err_w=%.2e  err_b=%.2e",
                err_w, err_b,
            )

        summary = {
            "protocol":          "SecAgg (Bonawitz et al. 2017)",
            "n_clients":         n,
            "n_survived":        len(survived),
            "n_dropped":         len(dropped),
            "threshold":         self.threshold,
            "round_seed":        round_seed,
            "masking_overhead_ms": round(elapsed_ms, 3),
            "verified":          verified,
            "max_weight_error":  round(err_w, 10),
            "bias_error":        round(err_b, 10),
        }

        return SecAggRound(
            aggregated_weights  = agg_w,
            aggregated_bias     = agg_b,
            n_clients_survived  = len(survived),
            n_clients_dropped   = len(dropped),
            masking_overhead_ms = elapsed_ms,
            verified            = verified,
            secagg_summary      = summary,
        )
